export { LoginPage } from './login-page'
export { RegisterPage } from './register-page'
export { ProfilePage } from './profile-page'
export { EditProfilePage } from './edit-profile-page'
export { ChangePasswordPage } from './change-password-page'